#!/usr/bin/python3
print ("\n")
print ("<html>")
print ("<head>")
print ("<title>First CGI Program</title>")
print ("</head>")
print ("<body>")
print ("<h2>Hello</h2>")
print ("</body>")
print ("</html>")